### ISSUE TITLE
Add /loop and /24-7?

### ISSUE THREAD

**Issue by Rstacx** [CyberedCake/DiscordMusicBot#29]
Can you add the two commands loop and 24/7?

**Comment by CyberedCake** [comment]
Not a bad idea, will get working on that. Note, school had started for me but I will work on it.

**Comment by CyberedCake** [comment]
Not a bad idea, will get working on that. Note, school had started for me but I will work on it.

**Comment by Rstacx** [comment]
Ok

**Comment by CyberedCake** [comment]
Just to confirm, is the 24/7 command like YouTube's autoplay? It just finds videos similar and plays them? Or do you have something else in mind?

**Comment by Rstacx** [comment]
> Just to confirm, is the 24/7 command like YouTube's autoplay? It just finds videos similar and plays them? Or do you have something else in mind?

YouTube live stream is available 24/7 in vc with 24/7 command.
When you play the song of your bot, an error message appears, take a look at it.

**Comment by CyberedCake** [comment]
Can you send me the error message? I can enter a live stream fine and it works. 

Also, I'm very much struggling to replicate the 24-7 behavior of other bots. For now, I'm going to make /loop and figure out your issue here then I'll look into something similar to /24-7.

**Comment by CyberedCake** [comment]
[Added the /loop song command](https://github.com/CyberedCake/DiscordMusicBot/commit/f71b05833de9b82c3476a2cfedfd8ff01a3fc805)

**Comment by Rstacx** [comment]
> [Added the /loop song command](https://github.com/CyberedCake/DiscordMusicBot/commit/f71b05833de9b82c3476a2cfedfd8ff01a3fc805)

Thanks

**Comment by CyberedCake** [comment]
I'm going to close this issue because `/loop song` was added and the 24/7 functionality you asked for seems to be in reference to YT live streams, which are currently supported.
